In [1]:
from etl.extract import extract_data_from_bigquery
import pandas as pd

df = extract_data_from_bigquery()

# set setting to show all columns
pd.set_option('display.max_columns', None)

INFO - Query returned 1000 rows and 9 columns

In [3]:
df.head(100)

,GLOBALEVENTID,SQLDATE,Actor1Name,Actor2Name,EventCode,ActionGeo_FullName,ActionGeo_CountryCode,ActionGeo_ADM1Code,SOURCEURL
0,1172856868,20240430,PALESTINIAN,ISRAEL,141,"California, United States",US,USCA,http://arabic.news.cn/20240430/a9473caf3bb8486...
1,1172856843,20240430,NIGER,COMMANDO,111,United States,US,US,https://malijet.com/actualte_dans_les_regions_...
2,1172856586,20240430,UNIVERSITY,CALIFORNIA,160,"California, United States",US,USCA,https://lajornadasanluis.com.mx/internacional/...
3,1172856756,20240430,ISRAEL,A US,1822,"California, United States",US,USCA,https://jang.com.pk/news/1345522
4,1172856872,20240430,GAZA,UNITED STATES,190,"California, United States",US,USCA,https://www.sakshi.com/telugu-news/internation...
...,...,...,...,...,...,...,...,...,...
95,1172852343,20240430,SCHOOL,LEGISLATOR,071,"Camanche, Iowa, United States",US,USIA,https://www.clintonherald.com/news/retiring-su...
96,1172852352,20240430,SCHOOL,UNITED STATES,010,"Camanche, Iowa, United States",US,USIA,https://www.clintonherald.com/news/retiring-su...
97,1172852188,20240430,CHRISTIAN,IOWA,046,"Missouri, United States",US,USMO,https://siouxcityjournal.com/news/state-region...
98,1172852969,20240430,UNITED STATES,PUPIL,010,"Camanche, Iowa, United States",US,USIA,https://www.clintonherald.com/news/retiring-su...
99,1172852977,20240430,UNITED STATES,SCHOOL,071,"Camanche, Iowa, United States",US,USIA,https://www.clintonherald.com/news/retiring-su...

In [3]:
# save 5 rows to csv
df.head().to_csv('data/5_rows.csv', index=False)